// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://virxaldfernftbborgow.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InZpcnhhbGRmZXJuZnRiYm9yZ293Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDQzODkxNTYsImV4cCI6MjA1OTk2NTE1Nn0.87VwcqA4RsZuZ0aZUwD4hzI-EjO_VaNI1oK7EaArn_k";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);